spring.datasource.url=jdbc:postgresql://localhost:5432/payflow
spring.datasource.username=payflow
spring.datasource.password=payflow123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG